import rtconfig
from building import *

cwd     = GetCurrentDir()
src     = Split("""
main.c
""")

if GetDepend(['Board_Using_Rocker']):
    src += Glob('func/rocker.c')
if GetDepend(['Board_Using_Rocker']):
    src += Glob('func/button.c')
	
group = DefineGroup('Applications', src, depend = [''])

Return('group')
