import rtconfig
from building import *

cwd     = GetCurrentDir()
src     = Split("""
mid_ad7739.c
mid_flash.c
mid_fram.c
""")

path = [cwd]

group = DefineGroup('Middle', src, depend = [''], CPPPATH = path)

Return('group')
